FROM python:3.7.3-stretch

RUN pip install torch==1.0.1 torchvision==0.2.2 pillow==6.1 fastai aiohttp asyncio uvicorn starlette

WORKDIR /workdir

EXPOSE 8501

COPY src /workdir/

RUN echo "cache bust"
ARG MODEL_DIR
ARG UTILS_DIR
RUN echo $MODEL_DIR
COPY $MODEL_DIR /workdir/model
COPY $UTILS_DIR /workdir/utils

ENTRYPOINT ["python3.7", "server.py", "serve"]
